module.exports = {
  js: 'JavaScript',
  javascript: 'JavaScript',
  sh: 'Shell',
  bash: 'Shell',
  actionscript: 'ActionScript',
  as: 'ActionScript',
  bat: 'BatchScript',
  c: 'C',
  cpp: 'C++',
  'c++': 'C++',
  csharp: 'C#',
  css: 'CSS',
  diff: 'Diff',
  patch: 'Patch',
  go: 'Go',
  html: 'HTML',
  md: 'Markdown',
  markdown: 'Markdown',
  php: 'PHP',
  sql: 'SQL',
  xml: 'XML',
  yaml: 'YAML',
};
